ARG base_image
FROM ${base_image}

WORKDIR $HOME
EXPOSE 8080

ENV STI_SCRIPTS_PATH=/usr/libexec/s2i

LABEL io.k8s.display-name="von-image s2i $image_tag" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,python,von-image,indy,hyperledger" \
      io.openshift.s2i.scripts-url="image:///${STI_SCRIPTS_PATH}"

# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH.
COPY --chown=indy:0 ./s2i/bin/. $STI_SCRIPTS_PATH

# Copy extra files to the image.
COPY --chown=indy:0 ./s2i/root/ /

USER root

# - In order to drop the root user, we have to make some directories world
#   writable as OpenShift default security model is to run the container
#   under random UID.
RUN usermod -a -G 0 indy && \
    chmod -R ug+rwx $STI_SCRIPTS_PATH /generate_container_user

USER 1001

# Set the default CMD to print the usage of the language image.
CMD $STI_SCRIPTS_PATH/usage
